=== FlavioDeCarvalhoPereira/Documents/SNIR2/XML/TP_XML-XSL-CSS/TP_XML-XSL-CSS/public_html/jo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT tableau (ligne*)>
<!ELEMENT ligne (pays,medaille,medaille,medaille,totalMedaille?)>
<!ELEMENT medaille (#PCDATA)>
<!ELEMENT pays EMPTY>

<!ELEMENT totalMedaille (#PCDATA)>

<!ATTLIST pays nomPays (USA|GrandeBretagne|Chine|Russie|Allemagne|Japon|France|CoreeSud|Italie|Australie) #REQUIRED>
<!ATTLIST medaille typeMedaille (OR|ARGENT|BRONZE) #REQUIRED>

=== FlavioDeCarvalhoPereira/Documents/SNIR2/XML/TP_XML-XSL-CSS/TP_XML-XSL-CSS/public_html/jo.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="jo.xsl" type="text/xsl" ?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE tableau SYSTEM "jo.dtd">


    <tableau>
        <ligne>            
            <pays nomPays="USA"/>
            <medaille typeMedaille ="OR"> 46</medaille>
            <medaille typeMedaille ="ARGENT"> 37</medaille>
            <medaille typeMedaille ="BRONZE"> 38</medaille>
            <totalMedaille>121</totalMedaille>
           
        </ligne>
        <ligne>
            <pays nomPays="GrandeBretagne"></pays>
            <medaille typeMedaille ="OR"> 27</medaille>
            <medaille typeMedaille ="ARGENT"> 23</medaille>
            <medaille typeMedaille ="BRONZE"> 17</medaille>
            <totalMedaille>67</totalMedaille>
           
        </ligne>
        <ligne>
            <pays nomPays="Chine"></pays>
            <medaille typeMedaille ="OR"> 26</medaille>
            <medaille typeMedaille ="ARGENT"> 18</medaille>
            <medaille typeMedaille ="BRONZE"> 26</medaille>
            <totalMedaille>70</totalMedaille>
            
        </ligne>
        <ligne>
            <pays nomPays="Russie"></pays>
            <medaille typeMedaille ="OR"> 19</medaille>
            <medaille typeMedaille ="ARGENT"> 18</medaille>
            <medaille typeMedaille ="BRONZE"> 19</medaille>
            <totalMedaille>56</totalMedaille>
            
        </ligne>
        <ligne>
            <pays nomPays="Allemagne"></pays>
            <medaille typeMedaille ="OR"> 17</medaille>
            <medaille typeMedaille ="ARGENT"> 10</medaille>
            <medaille typeMedaille ="BRONZE"> 15</medaille>
            <totalMedaille>42</totalMedaille>
            
        </ligne>
        <ligne>
            <pays nomPays="Japon"></pays>
            <medaille typeMedaille ="OR"> 12</medaille>
            <medaille typeMedaille ="ARGENT"> 8</medaille>
            <medaille typeMedaille ="BRONZE"> 21</medaille>
            <totalMedaille>41</totalMedaille>
           
        </ligne>
        <ligne>
            <pays nomPays="France"></pays>
            <medaille typeMedaille ="OR"> 10</medaille>
            <medaille typeMedaille ="ARGENT"> 18</medaille>
            <medaille typeMedaille ="BRONZE"> 14</medaille>
            <totalMedaille>42</totalMedaille>
            
        </ligne>
        <ligne>
            <pays nomPays="CoreeSud"/>
            <medaille typeMedaille ="OR"> 9</medaille>
            <medaille typeMedaille ="ARGENT"> 3</medaille>
            <medaille typeMedaille ="BRONZE"> 9</medaille>
            <totalMedaille>21</totalMedaille>
            
        </ligne>
        <ligne>
            <pays nomPays="Italie"></pays>
            <medaille typeMedaille ="OR"> 8</medaille>
            <medaille typeMedaille ="ARGENT"> 12</medaille>
            <medaille typeMedaille ="BRONZE"> 8</medaille>
            <totalMedaille>28</totalMedaille>
            
        </ligne>
        <ligne>
            <pays nomPays="Australie"></pays>
            <medaille typeMedaille ="OR"> 8</medaille>
            <medaille typeMedaille ="ARGENT"> 11</medaille>
            <medaille typeMedaille ="BRONZE"> 10</medaille>
            <totalMedaille>29</totalMedaille>
            
        </ligne>
    </tableau>
