=== FlavioDeCarvalhoPereira/Documents/SNIR2/XML/TD_XML-DTD/public_html/bibliotheque.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT biblioteque (allee+)>
<!ELEMENT allee (rayon+)>
<!ELEMENT rayon (ouvrage*)>
<!ELEMENT ouvrage (titre,auteur?)>

<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>

<!ATTLIST allee numero CDATA #REQUIRED>
<!ATTLIST rayon numero CDATA #IMPLIED>
<!ATTLIST ouvrage numero CDATA #IMPLIED>
<!ATTLIST ouvrage type (litterature|manuelScolaire|periodique|scienceEtTechnique) "litterature">

=== FlavioDeCarvalhoPereira/Documents/SNIR2/XML/TD_XML-XSL/public_html/bibliotheque.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="xsl.xsl" type="text/xsl" ?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE biblioteque SYSTEM "bibliotheque.dtd">

<biblioteque>

    <allee numero ="1">
        
        <rayon numero = "1">
            
            <ouvrage >
                <titre>Le papillon des Ã©toiles</titre>
                <auteur>Bernard WERBER</auteur>
            </ouvrage>
            
            <ouvrage type ="manuelScolaire" numero ="">
                <titre>Les Formes de base</titre>
                <auteur>Daniele Dumont</auteur>
            </ouvrage>
            
            <ouvrage type ="scienceEtTechnique" >
                <titre>XML et XSL : Les feuilles de style XML</titre>
                <auteur>Cyril Vincent</auteur>
            </ouvrage>
            
        </rayon>
        
        <rayon numero = "2">
            
            <ouvrage type ="periodique" numero ="102">
                <titre>LINUX Magazine</titre>
                <auteur></auteur>
            </ouvrage>
            
            <ouvrage type ="periodique">
                <titre>Closer</titre>
                <auteur></auteur>
            </ouvrage>
            
            <ouvrage numero ="1">
                <titre>Harry Potter</titre>
                <auteur>JK Rollin</auteur>
            </ouvrage>
            
        </rayon>
        
    </allee>
    
    <allee numero="2">
        <rayon numero="1">
            
            <ouvrage  numero ="31">
                <titre>Jeu de nains</titre>
                <auteur>Terry Pratchett</auteur>
            </ouvrage>
            
        </rayon>
        
        <rayon numero="2">
            
            <ouvrage  numero ="2">
                <titre>Fondation</titre>
                <auteur>Isaac Asimov</auteur>
            </ouvrage>
            
            <ouvrage type ="scienceEtTechnique">
                <titre>Ajax, jQuery et PHP</titre>
                <auteur>Jean-marie Defrance</auteur>
            </ouvrage>
            
        </rayon>
        
    </allee>

</biblioteque>
